const shoes = [
  {
    id: 1,
    style: "m",
    name: "Aviator",
    price: 150,
    brand: "Nike",
    img: "shoe1.jpg",
  },
  {
    id: 2,
    style: "f",
    name: "Highlands",
    price: 125,
    brand: "Adidas",
    img: "shoe2.jpg",
  },
  {
    id: 3,
    style: "f",
    name: "Classy X",
    price: 320,
    brand: "Saucony",
    img: "shoe3.jpg",
  },
  {
    id: 4,
    style: "k",
    name: "Jeffersons",
    price: 140,
    brand: "Nike",
    img: "shoe4.jpg",
  },
  {
    id: 5,
    style: "k",
    name: "Prime Kicks",
    price: 150,
    brand: "Adidas",
    img: "shoe5.jpg",
  },
  {
    id: 6,
    style: "m",
    name: "Aviator",
    price: 150,
    brand: "Nike",
    img: "shoe6.jpg",
  },
  {
    id: 7,
    style: "f",
    name: "Highlands",
    price: 125,
    brand: "Adidas",
    img: "shoe7.jpg",
  },
  {
    id: 8,
    style: "f",
    name: "Classy X",
    price: 320,
    brand: "Saucony",
    img: "shoe8.jpg",
  },
  {
    id: 9,
    style: "k",
    name: "Jeffersons",
    price: 140,
    brand: "Nike",
    img: "shoe9.jpg",
  },
  {
    id: 10,
    style: "k",
    name: "Prime Kicks",
    price: 150,
    brand: "Adidas",
    img: "shoe10.jpg",
  },
  {
    id: 11,
    style: "m",
    name: "Aviator",
    price: 150,
    brand: "Nike",
    img: "shoe11.jpg",
  },
  {
    id: 12,
    style: "f",
    name: "Highlands",
    price: 125,
    brand: "Adidas",
    img: "shoe12.jpg",
  },
  {
    id: 13,
    style: "f",
    name: "Classy X",
    price: 320,
    brand: "Saucony",
    img: "shoe13.jpg",
  },
  {
    id: 14,
    style: "k",
    name: "Jeffersons",
    price: 140,
    brand: "Nike",
    img: "shoe14.jpg",
  },
  {
    id: 15,
    style: "k",
    name: "Prime Kicks",
    price: 150,
    brand: "Adidas",
    img: "shoe15.jpg",
  },
];

export default shoes;
